# Generated by Django 3.2.9 on 2022-01-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
