# Generated by Django 3.2.9 on 2022-01-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_img',
            field=models.ImageField(upload_to='media/profile/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='picture',
            field=models.ImageField(upload_to='media/picture/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='media/portfolio/'),
        ),
    ]
