# Generated by Django 3.2.9 on 2022-01-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220114_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skiil_name',
            new_name='skill_name',
        ),
    ]
